import re
import sys

output, mapper_files = sys.argv[1], sys.argv[2]
mapper_nums = re.findall(r"mapper_(\d+)", mapper_files)

externs = "\n".join(f"extern const struct NesCartMapperInterface mapper_{n};" for n in mapper_nums)
arr = "\n".join(f"    [{int(n)}] = &mapper_{n}," for n in mapper_nums)

with open(output, 'wt') as fp:
    fp.write(f"""// GENERATED BY {__file__}. DD NOT EDIT.

#include <nes_cart.h>

{externs}

const struct NesCartMapperInterface *const mapper_table[] = {{
{arr}
}};

const size_t mapper_table_size = sizeof(mapper_table) / sizeof(mapper_table[0]);
""")
#
